#!/bin/sh
# Export the operator's CRD schemas for the docs' config generator (docs/generator/): one
# `schemas.js` carrying every kind's group, version, scope and openAPIV3Schema, read from the
# checked-in charts/weebo-si-operator/crds/ — which scripts/crd-regen.sh keeps equal to the Rust
# types. A script file rather than JSON fetched at runtime, so the page also works opened
# straight from disk (file://), where a browser refuses `fetch`.
#
#   scripts/docs-schemas.sh            regenerate docs/generator/schemas.js
#   scripts/docs-schemas.sh --check    exit 1 if it is stale, write nothing
#
# Needs mikefarah's yq v4 (mise.toml; preinstalled on GitHub-hosted ubuntu runners).
set -eu

REPO_ROOT=$(unset CDPATH; cd -- "$(dirname -- "$0")/.." && pwd)
cd "$REPO_ROOT"

CRDS="charts/weebo-si-operator/crds/weebosiconfigs.hardening.weebo.io.yaml
charts/weebo-si-operator/crds/weebositeams.hardening.weebo.io.yaml
charts/weebo-si-operator/crds/weebosiusers.hardening.weebo.io.yaml"
OUT="docs/generator/schemas.js"

check_only=0
case "${1:-}" in
  --check) check_only=1 ;;
  '') ;;
  *) echo "usage: $0 [--check]" >&2; exit 2 ;;
esac

if ! command -v yq >/dev/null 2>&1; then
  echo "docs-schemas: yq not installed — run 'mise install'" >&2
  exit 1
fi

generated=$(mktemp)
trap 'rm -f "$generated"' EXIT INT TERM

{
  echo "// Generated by scripts/docs-schemas.sh from charts/weebo-si-operator/crds/ — do not edit;"
  echo "// run 'task docs:schemas'."
  echo "window.WEEBO_CRDS = ["
  for crd in $CRDS; do
    # The storage version is the one the apiserver persists, and the one to write. `$v` is a yq
    # variable, not a shell one.
    # shellcheck disable=SC2016
    yq -o=json -I=2 '
      (.spec.versions[] | select(.storage)) as $v
      | {
          "group": .spec.group,
          "version": $v.name,
          "kind": .spec.names.kind,
          "plural": .spec.names.plural,
          "scope": .spec.scope,
          "schema": $v.schema.openAPIV3Schema
        }' "$crd"
    echo ","
  done
  echo "];"
} > "$generated"

if [ -f "$OUT" ] && cmp -s "$generated" "$OUT"; then
  [ "$check_only" = 1 ] || echo "docs-schemas: $OUT already up to date"
  exit 0
fi

if [ "$check_only" = 1 ]; then
  echo "docs-schemas: $OUT is stale — run 'task docs:schemas'" >&2
  diff -u "$OUT" "$generated" >&2 || true
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
cat "$generated" > "$OUT"
echo "docs-schemas: regenerated $OUT"
