{{- if ne .Values.certificates.provider "none" }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "weebo-si-operator.fullname" . }}-devworkspaces
  labels:
    {{- include "weebo-si-operator.webhook.selectorLabels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.certificates.provider "cert-manager" }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "weebo-si-operator.webhookServiceName" . }}
    {{- else if eq .Values.certificates.provider "openshift" }}
    service.beta.openshift.io/inject-cabundle: "true"
    {{- end }}
webhooks:
  - name: devworkspaces.hardening.weebo.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    matchPolicy: Equivalent
    failurePolicy: Fail
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    reinvocationPolicy: IfNeeded
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["controller.devfile.io"]
        apiVersions: ["v1alpha1"]
        resources: ["devworkspaces"]
        scope: Namespaced
    namespaceSelector:
      matchExpressions:
        - key: {{ .Values.namespaceExclusionLabel }}
          operator: DoesNotExist
    clientConfig:
      service:
        name: {{ include "weebo-si-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate/v1alpha1/devworkspaces
        port: {{ .Values.webhook.service.port }}
{{- end }}
